#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : assimp
Version  : 5.0.1
Release  : 6
URL      : https://github.com/assimp/assimp/archive/v5.0.1/assimp-5.0.1.tar.gz
Source0  : https://github.com/assimp/assimp/archive/v5.0.1/assimp-5.0.1.tar.gz
Summary  : Import various well-known 3D model formats in an uniform manner.
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 LGPL-3.0 MIT Unlicense
Requires: assimp-bin = %{version}-%{release}
Requires: assimp-lib = %{version}-%{release}
Requires: assimp-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : freeglut-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : python3
BuildRequires : qtbase-extras
BuildRequires : zlib-dev

%description
See Readme.md

%package bin
Summary: bin components for the assimp package.
Group: Binaries
Requires: assimp-license = %{version}-%{release}

%description bin
bin components for the assimp package.


%package dev
Summary: dev components for the assimp package.
Group: Development
Requires: assimp-lib = %{version}-%{release}
Requires: assimp-bin = %{version}-%{release}
Provides: assimp-devel = %{version}-%{release}
Requires: assimp = %{version}-%{release}

%description dev
dev components for the assimp package.


%package lib
Summary: lib components for the assimp package.
Group: Libraries
Requires: assimp-license = %{version}-%{release}

%description lib
lib components for the assimp package.


%package license
Summary: license components for the assimp package.
Group: Default

%description license
license components for the assimp package.


%prep
%setup -q -n assimp-5.0.1
cd %{_builddir}/assimp-5.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585193441
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DASSIMP_LIB_INSTALL_DIR=lib64
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1585193441
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/assimp
cp %{_builddir}/assimp-5.0.1/LICENSE %{buildroot}/usr/share/package-licenses/assimp/e17e89e763a2dee69f8930e7f292e836329003ca
cp %{_builddir}/assimp-5.0.1/contrib/clipper/License.txt %{buildroot}/usr/share/package-licenses/assimp/e4b7506d9f00ccf4a353cd90c412d960284b776c
cp %{_builddir}/assimp-5.0.1/contrib/gtest/LICENSE %{buildroot}/usr/share/package-licenses/assimp/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/assimp-5.0.1/contrib/openddlparser/LICENSE %{buildroot}/usr/share/package-licenses/assimp/2cb5e9994220f1b4cbcb8fe617c5936a33414d6c
cp %{_builddir}/assimp-5.0.1/contrib/poly2tri/LICENSE %{buildroot}/usr/share/package-licenses/assimp/3c4a0cf53278b001dd25ca8dea8d543fc0374181
cp %{_builddir}/assimp-5.0.1/contrib/rapidjson/license.txt %{buildroot}/usr/share/package-licenses/assimp/47ab05791f28173ad2b82f25c2b5c7fc06252b4d
cp %{_builddir}/assimp-5.0.1/contrib/zip/UNLICENSE %{buildroot}/usr/share/package-licenses/assimp/37b4d8fc2380f796ce8ca0cb52c23238b9ed8163
cp %{_builddir}/assimp-5.0.1/contrib/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/assimp/3f317fbb3e08fd99169d2e77105d562ea0e482c7
cp %{_builddir}/assimp-5.0.1/packaging/windows-innosetup/LICENSE.rtf %{buildroot}/usr/share/package-licenses/assimp/ae6afd9b31956c3be7ffcfa0f719aa4769042a9d
cp %{_builddir}/assimp-5.0.1/test/models-nonbsd/Ogre/OgreSDK/LICENSE %{buildroot}/usr/share/package-licenses/assimp/da5043f355a0fc628eb5877ba44e42f40582bdda
cp %{_builddir}/assimp-5.0.1/test/models-nonbsd/PLY/ant-half.ply.license %{buildroot}/usr/share/package-licenses/assimp/e203d4ef09d404fa5c03cf6590e44231665be689
cp %{_builddir}/assimp-5.0.1/test/models/glTF2/glTF-Asset-Generator/LICENSE %{buildroot}/usr/share/package-licenses/assimp/b4152265e76a4e82d7e34bc1b95e07bda51bca73
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/assimp

%files dev
%defattr(-,root,root,-)
/usr/include/assimp/BaseImporter.h
/usr/include/assimp/Bitmap.h
/usr/include/assimp/BlobIOSystem.h
/usr/include/assimp/ByteSwapper.h
/usr/include/assimp/Compiler/poppack1.h
/usr/include/assimp/Compiler/pstdint.h
/usr/include/assimp/Compiler/pushpack1.h
/usr/include/assimp/CreateAnimMesh.h
/usr/include/assimp/DefaultIOStream.h
/usr/include/assimp/DefaultIOSystem.h
/usr/include/assimp/DefaultLogger.hpp
/usr/include/assimp/Defines.h
/usr/include/assimp/Exceptional.h
/usr/include/assimp/Exporter.hpp
/usr/include/assimp/GenericProperty.h
/usr/include/assimp/Hash.h
/usr/include/assimp/IOStream.hpp
/usr/include/assimp/IOStreamBuffer.h
/usr/include/assimp/IOSystem.hpp
/usr/include/assimp/Importer.hpp
/usr/include/assimp/LineSplitter.h
/usr/include/assimp/LogAux.h
/usr/include/assimp/LogStream.hpp
/usr/include/assimp/Logger.hpp
/usr/include/assimp/Macros.h
/usr/include/assimp/MathFunctions.h
/usr/include/assimp/MemoryIOWrapper.h
/usr/include/assimp/NullLogger.hpp
/usr/include/assimp/ParsingUtils.h
/usr/include/assimp/Profiler.h
/usr/include/assimp/ProgressHandler.hpp
/usr/include/assimp/RemoveComments.h
/usr/include/assimp/SGSpatialSort.h
/usr/include/assimp/SceneCombiner.h
/usr/include/assimp/SkeletonMeshBuilder.h
/usr/include/assimp/SmoothingGroups.h
/usr/include/assimp/SmoothingGroups.inl
/usr/include/assimp/SpatialSort.h
/usr/include/assimp/StandardShapes.h
/usr/include/assimp/StreamReader.h
/usr/include/assimp/StreamWriter.h
/usr/include/assimp/StringComparison.h
/usr/include/assimp/StringUtils.h
/usr/include/assimp/Subdivision.h
/usr/include/assimp/TinyFormatter.h
/usr/include/assimp/Vertex.h
/usr/include/assimp/XMLTools.h
/usr/include/assimp/ZipArchiveIOSystem.h
/usr/include/assimp/aabb.h
/usr/include/assimp/ai_assert.h
/usr/include/assimp/anim.h
/usr/include/assimp/camera.h
/usr/include/assimp/cexport.h
/usr/include/assimp/cfileio.h
/usr/include/assimp/cimport.h
/usr/include/assimp/color4.h
/usr/include/assimp/color4.inl
/usr/include/assimp/config.h
/usr/include/assimp/defs.h
/usr/include/assimp/fast_atof.h
/usr/include/assimp/importerdesc.h
/usr/include/assimp/irrXMLWrapper.h
/usr/include/assimp/light.h
/usr/include/assimp/material.h
/usr/include/assimp/material.inl
/usr/include/assimp/matrix3x3.h
/usr/include/assimp/matrix3x3.inl
/usr/include/assimp/matrix4x4.h
/usr/include/assimp/matrix4x4.inl
/usr/include/assimp/mesh.h
/usr/include/assimp/metadata.h
/usr/include/assimp/pbrmaterial.h
/usr/include/assimp/postprocess.h
/usr/include/assimp/qnan.h
/usr/include/assimp/quaternion.h
/usr/include/assimp/quaternion.inl
/usr/include/assimp/scene.h
/usr/include/assimp/texture.h
/usr/include/assimp/types.h
/usr/include/assimp/vector2.h
/usr/include/assimp/vector2.inl
/usr/include/assimp/vector3.h
/usr/include/assimp/vector3.inl
/usr/include/assimp/version.h
/usr/lib64/cmake/assimp-5.0/assimp-config-version.cmake
/usr/lib64/cmake/assimp-5.0/assimp-config.cmake
/usr/lib64/cmake/assimp-5.0/assimpTargets-release.cmake
/usr/lib64/cmake/assimp-5.0/assimpTargets.cmake
/usr/lib64/libassimp.so
/usr/lib64/pkgconfig/assimp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libassimp.so.5
/usr/lib64/libassimp.so.5.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/assimp/2cb5e9994220f1b4cbcb8fe617c5936a33414d6c
/usr/share/package-licenses/assimp/37b4d8fc2380f796ce8ca0cb52c23238b9ed8163
/usr/share/package-licenses/assimp/3c4a0cf53278b001dd25ca8dea8d543fc0374181
/usr/share/package-licenses/assimp/3f317fbb3e08fd99169d2e77105d562ea0e482c7
/usr/share/package-licenses/assimp/47ab05791f28173ad2b82f25c2b5c7fc06252b4d
/usr/share/package-licenses/assimp/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/assimp/ae6afd9b31956c3be7ffcfa0f719aa4769042a9d
/usr/share/package-licenses/assimp/b4152265e76a4e82d7e34bc1b95e07bda51bca73
/usr/share/package-licenses/assimp/da5043f355a0fc628eb5877ba44e42f40582bdda
/usr/share/package-licenses/assimp/e17e89e763a2dee69f8930e7f292e836329003ca
/usr/share/package-licenses/assimp/e203d4ef09d404fa5c03cf6590e44231665be689
/usr/share/package-licenses/assimp/e4b7506d9f00ccf4a353cd90c412d960284b776c
